FROM node:24-alpine

WORKDIR /app

RUN corepack enable \
    && corepack prepare pnpm@10.34.0 --activate

ENV HUSKY=0

COPY package.json pnpm-lock.yaml ./

RUN CI=true HUSKY=0 pnpm install --frozen-lockfile

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "80"]