export { api } from './services/client'
export { courseService } from './services/courses'
export { archiveService } from './services/archives'
export { authService } from './services/auth'
export { memeService } from './services/meme'
export { statisticsService } from './services/statistics'
export { notificationService } from './services/notifications'
export { homepageSloganService } from './services/homepageSlogans'
export { themeManagementService } from './services/themeManagement'
export { discussionService } from './services/discussion'
export { reportService } from './services/reports'
export { userService } from './services/users'
export { aboutUsService } from './services/aboutUs'
export { wishService } from './services/wishes'
export * from './services/admin'
